language: c
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - ocaml-native-compilers
    - opam

script: bash -ex .travis-ci.sh
env:
  # - OPAM_SWITCH=system
  # - OPAM_SWITCH=3.12.1
  # - OPAM_SWITCH=4.01.0
  - OPAM_SWITCH=4.02.3
  - OPAM_SWITCH=4.03.0+trunk
  - OPAM_SWITCH=4.03.0+flambda
cache:
  directories:
  - $HOME/.opam
